// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1TPGKufRnvbev-CPaVOFRzoSA5gYKCOE',
    appId: '1:794244907172:web:a3c6a835c49997c880e631',
    messagingSenderId: '794244907172',
    projectId: 'fb-auth-riverpod-2024',
    authDomain: 'fb-auth-riverpod-2024.firebaseapp.com',
    storageBucket: 'fb-auth-riverpod-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZpxNtRjT6FjMVNFqc7I4BDCOnRpqotrc',
    appId: '1:794244907172:android:075229257fdd645680e631',
    messagingSenderId: '794244907172',
    projectId: 'fb-auth-riverpod-2024',
    storageBucket: 'fb-auth-riverpod-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9SXhoa-TNSvABqW3RMtbj24tfEQZg0eo',
    appId: '1:794244907172:ios:b7e9bdd835a47c9a80e631',
    messagingSenderId: '794244907172',
    projectId: 'fb-auth-riverpod-2024',
    storageBucket: 'fb-auth-riverpod-2024.appspot.com',
    iosBundleId: 'com.example.fbAuthRiverpod',
  );
}
